title: First Class Citizen
email: amhcohc@gmail.com
description: 'Java, Spring, MySQL, JPA, Python, Swift'
baseurl: ''
url: ''
github_username: amhcohc
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
